# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: maven:3.6.3-ibmjava-8-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker images
      run: docker-compose up --build
